package common.entity;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-from-proto.proto

public final class UserFromProto {
    private UserFromProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface UserOrBuilder extends
            // @@protoc_insertion_point(interface_extends:User)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string username = 1;</code>
         * @return The username.
         */
        java.lang.String getUsername();
        /**
         * <code>string username = 1;</code>
         * @return The bytes for username.
         */
        com.google.protobuf.ByteString
        getUsernameBytes();

        /**
         * <code>string sex = 2;</code>
         * @return The sex.
         */
        java.lang.String getSex();
        /**
         * <code>string sex = 2;</code>
         * @return The bytes for sex.
         */
        com.google.protobuf.ByteString
        getSexBytes();

        /**
         * <code>int32 age = 3;</code>
         * @return The age.
         */
        int getAge();

        /**
         * <code>.User.Team team = 4;</code>
         * @return Whether the team field is set.
         */
        boolean hasTeam();
        /**
         * <code>.User.Team team = 4;</code>
         * @return The team.
         */
        UserFromProto.User.Team getTeam();
        /**
         * <code>.User.Team team = 4;</code>
         */
        UserFromProto.User.TeamOrBuilder getTeamOrBuilder();

        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        java.util.List<UserFromProto.User.Team>
        getTeamListList();
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        UserFromProto.User.Team getTeamList(int index);
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        int getTeamListCount();
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        java.util.List<? extends UserFromProto.User.TeamOrBuilder>
        getTeamListOrBuilderList();
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        UserFromProto.User.TeamOrBuilder getTeamListOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class User extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:User)
            UserOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use User.newBuilder() to construct.
        private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private User() {
            username_ = "";
            sex_ = "";
            teamList_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new User();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private User(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            username_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            sex_ = s;
                            break;
                        }
                        case 24: {

                            age_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            UserFromProto.User.Team.Builder subBuilder = null;
                            if (team_ != null) {
                                subBuilder = team_.toBuilder();
                            }
                            team_ = input.readMessage(UserFromProto.User.Team.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(team_);
                                team_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 42: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                teamList_ = new java.util.ArrayList<UserFromProto.User.Team>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            teamList_.add(
                                    input.readMessage(UserFromProto.User.Team.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    teamList_ = java.util.Collections.unmodifiableList(teamList_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return UserFromProto.internal_static_User_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return UserFromProto.internal_static_User_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UserFromProto.User.class, UserFromProto.User.Builder.class);
        }

        public interface TeamOrBuilder extends
                // @@protoc_insertion_point(interface_extends:User.Team)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string ceo = 1;</code>
             * @return The ceo.
             */
            java.lang.String getCeo();
            /**
             * <code>string ceo = 1;</code>
             * @return The bytes for ceo.
             */
            com.google.protobuf.ByteString
            getCeoBytes();

            /**
             * <code>string cto = 2;</code>
             * @return The cto.
             */
            java.lang.String getCto();
            /**
             * <code>string cto = 2;</code>
             * @return The bytes for cto.
             */
            com.google.protobuf.ByteString
            getCtoBytes();

            /**
             * <code>string cfo = 3;</code>
             * @return The cfo.
             */
            java.lang.String getCfo();
            /**
             * <code>string cfo = 3;</code>
             * @return The bytes for cfo.
             */
            com.google.protobuf.ByteString
            getCfoBytes();
        }
        /**
         * Protobuf type {@code User.Team}
         */
        public static final class Team extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:User.Team)
                TeamOrBuilder {
            private static final long serialVersionUID = 0L;
            // Use Team.newBuilder() to construct.
            private Team(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }
            private Team() {
                ceo_ = "";
                cto_ = "";
                cfo_ = "";
            }

            @java.lang.Override
            @SuppressWarnings({"unused"})
            protected java.lang.Object newInstance(
                    UnusedPrivateParameter unused) {
                return new Team();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }
            private Team(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();

                                ceo_ = s;
                                break;
                            }
                            case 18: {
                                java.lang.String s = input.readStringRequireUtf8();

                                cto_ = s;
                                break;
                            }
                            case 26: {
                                java.lang.String s = input.readStringRequireUtf8();

                                cfo_ = s;
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return UserFromProto.internal_static_User_Team_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return UserFromProto.internal_static_User_Team_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UserFromProto.User.Team.class, UserFromProto.User.Team.Builder.class);
            }

            public static final int CEO_FIELD_NUMBER = 1;
            private volatile java.lang.Object ceo_;
            /**
             * <code>string ceo = 1;</code>
             * @return The ceo.
             */
            @java.lang.Override
            public java.lang.String getCeo() {
                java.lang.Object ref = ceo_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ceo_ = s;
                    return s;
                }
            }
            /**
             * <code>string ceo = 1;</code>
             * @return The bytes for ceo.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getCeoBytes() {
                java.lang.Object ref = ceo_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ceo_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int CTO_FIELD_NUMBER = 2;
            private volatile java.lang.Object cto_;
            /**
             * <code>string cto = 2;</code>
             * @return The cto.
             */
            @java.lang.Override
            public java.lang.String getCto() {
                java.lang.Object ref = cto_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    cto_ = s;
                    return s;
                }
            }
            /**
             * <code>string cto = 2;</code>
             * @return The bytes for cto.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getCtoBytes() {
                java.lang.Object ref = cto_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    cto_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int CFO_FIELD_NUMBER = 3;
            private volatile java.lang.Object cfo_;
            /**
             * <code>string cfo = 3;</code>
             * @return The cfo.
             */
            @java.lang.Override
            public java.lang.String getCfo() {
                java.lang.Object ref = cfo_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    cfo_ = s;
                    return s;
                }
            }
            /**
             * <code>string cfo = 3;</code>
             * @return The bytes for cfo.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getCfoBytes() {
                java.lang.Object ref = cfo_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    cfo_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            private byte memoizedIsInitialized = -1;
            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (!getCeoBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ceo_);
                }
                if (!getCtoBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cto_);
                }
                if (!getCfoBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cfo_);
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (!getCeoBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ceo_);
                }
                if (!getCtoBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cto_);
                }
                if (!getCfoBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cfo_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof UserFromProto.User.Team)) {
                    return super.equals(obj);
                }
                UserFromProto.User.Team other = (UserFromProto.User.Team) obj;

                if (!getCeo()
                        .equals(other.getCeo())) return false;
                if (!getCto()
                        .equals(other.getCto())) return false;
                if (!getCfo()
                        .equals(other.getCfo())) return false;
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + CEO_FIELD_NUMBER;
                hash = (53 * hash) + getCeo().hashCode();
                hash = (37 * hash) + CTO_FIELD_NUMBER;
                hash = (53 * hash) + getCto().hashCode();
                hash = (37 * hash) + CFO_FIELD_NUMBER;
                hash = (53 * hash) + getCfo().hashCode();
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static UserFromProto.User.Team parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static UserFromProto.User.Team parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static UserFromProto.User.Team parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static UserFromProto.User.Team parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static UserFromProto.User.Team parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static UserFromProto.User.Team parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static UserFromProto.User.Team parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }
            public static UserFromProto.User.Team parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }
            public static UserFromProto.User.Team parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }
            public static UserFromProto.User.Team parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }
            public static UserFromProto.User.Team parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }
            public static UserFromProto.User.Team parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() { return newBuilder(); }
            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }
            public static Builder newBuilder(UserFromProto.User.Team prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }
            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }
            /**
             * Protobuf type {@code User.Team}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:User.Team)
                    UserFromProto.User.TeamOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return UserFromProto.internal_static_User_Team_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return UserFromProto.internal_static_User_Team_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    UserFromProto.User.Team.class, UserFromProto.User.Team.Builder.class);
                }

                // Construct using UserFromProto.User.Team.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }
                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }
                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    ceo_ = "";

                    cto_ = "";

                    cfo_ = "";

                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return UserFromProto.internal_static_User_Team_descriptor;
                }

                @java.lang.Override
                public UserFromProto.User.Team getDefaultInstanceForType() {
                    return UserFromProto.User.Team.getDefaultInstance();
                }

                @java.lang.Override
                public UserFromProto.User.Team build() {
                    UserFromProto.User.Team result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public UserFromProto.User.Team buildPartial() {
                    UserFromProto.User.Team result = new UserFromProto.User.Team(this);
                    result.ceo_ = ceo_;
                    result.cto_ = cto_;
                    result.cfo_ = cfo_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }
                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }
                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }
                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }
                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }
                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }
                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof UserFromProto.User.Team) {
                        return mergeFrom((UserFromProto.User.Team)other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(UserFromProto.User.Team other) {
                    if (other == UserFromProto.User.Team.getDefaultInstance()) return this;
                    if (!other.getCeo().isEmpty()) {
                        ceo_ = other.ceo_;
                        onChanged();
                    }
                    if (!other.getCto().isEmpty()) {
                        cto_ = other.cto_;
                        onChanged();
                    }
                    if (!other.getCfo().isEmpty()) {
                        cfo_ = other.cfo_;
                        onChanged();
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    UserFromProto.User.Team parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (UserFromProto.User.Team) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private java.lang.Object ceo_ = "";
                /**
                 * <code>string ceo = 1;</code>
                 * @return The ceo.
                 */
                public java.lang.String getCeo() {
                    java.lang.Object ref = ceo_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        ceo_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>string ceo = 1;</code>
                 * @return The bytes for ceo.
                 */
                public com.google.protobuf.ByteString
                getCeoBytes() {
                    java.lang.Object ref = ceo_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        ceo_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>string ceo = 1;</code>
                 * @param value The ceo to set.
                 * @return This builder for chaining.
                 */
                public Builder setCeo(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    ceo_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>string ceo = 1;</code>
                 * @return This builder for chaining.
                 */
                public Builder clearCeo() {

                    ceo_ = getDefaultInstance().getCeo();
                    onChanged();
                    return this;
                }
                /**
                 * <code>string ceo = 1;</code>
                 * @param value The bytes for ceo to set.
                 * @return This builder for chaining.
                 */
                public Builder setCeoBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    ceo_ = value;
                    onChanged();
                    return this;
                }

                private java.lang.Object cto_ = "";
                /**
                 * <code>string cto = 2;</code>
                 * @return The cto.
                 */
                public java.lang.String getCto() {
                    java.lang.Object ref = cto_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        cto_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>string cto = 2;</code>
                 * @return The bytes for cto.
                 */
                public com.google.protobuf.ByteString
                getCtoBytes() {
                    java.lang.Object ref = cto_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        cto_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>string cto = 2;</code>
                 * @param value The cto to set.
                 * @return This builder for chaining.
                 */
                public Builder setCto(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    cto_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>string cto = 2;</code>
                 * @return This builder for chaining.
                 */
                public Builder clearCto() {

                    cto_ = getDefaultInstance().getCto();
                    onChanged();
                    return this;
                }
                /**
                 * <code>string cto = 2;</code>
                 * @param value The bytes for cto to set.
                 * @return This builder for chaining.
                 */
                public Builder setCtoBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    cto_ = value;
                    onChanged();
                    return this;
                }

                private java.lang.Object cfo_ = "";
                /**
                 * <code>string cfo = 3;</code>
                 * @return The cfo.
                 */
                public java.lang.String getCfo() {
                    java.lang.Object ref = cfo_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        cfo_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>string cfo = 3;</code>
                 * @return The bytes for cfo.
                 */
                public com.google.protobuf.ByteString
                getCfoBytes() {
                    java.lang.Object ref = cfo_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        cfo_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>string cfo = 3;</code>
                 * @param value The cfo to set.
                 * @return This builder for chaining.
                 */
                public Builder setCfo(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    cfo_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>string cfo = 3;</code>
                 * @return This builder for chaining.
                 */
                public Builder clearCfo() {

                    cfo_ = getDefaultInstance().getCfo();
                    onChanged();
                    return this;
                }
                /**
                 * <code>string cfo = 3;</code>
                 * @param value The bytes for cfo to set.
                 * @return This builder for chaining.
                 */
                public Builder setCfoBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    cfo_ = value;
                    onChanged();
                    return this;
                }
                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:User.Team)
            }

            // @@protoc_insertion_point(class_scope:User.Team)
            private static final UserFromProto.User.Team DEFAULT_INSTANCE;
            static {
                DEFAULT_INSTANCE = new UserFromProto.User.Team();
            }

            public static UserFromProto.User.Team getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<Team>
                    PARSER = new com.google.protobuf.AbstractParser<Team>() {
                @java.lang.Override
                public Team parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Team(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<Team> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<Team> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public UserFromProto.User.Team getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        public static final int USERNAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object username_;
        /**
         * <code>string username = 1;</code>
         * @return The username.
         */
        @java.lang.Override
        public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                username_ = s;
                return s;
            }
        }
        /**
         * <code>string username = 1;</code>
         * @return The bytes for username.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SEX_FIELD_NUMBER = 2;
        private volatile java.lang.Object sex_;
        /**
         * <code>string sex = 2;</code>
         * @return The sex.
         */
        @java.lang.Override
        public java.lang.String getSex() {
            java.lang.Object ref = sex_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                sex_ = s;
                return s;
            }
        }
        /**
         * <code>string sex = 2;</code>
         * @return The bytes for sex.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSexBytes() {
            java.lang.Object ref = sex_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                sex_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGE_FIELD_NUMBER = 3;
        private int age_;
        /**
         * <code>int32 age = 3;</code>
         * @return The age.
         */
        @java.lang.Override
        public int getAge() {
            return age_;
        }

        public static final int TEAM_FIELD_NUMBER = 4;
        private UserFromProto.User.Team team_;
        /**
         * <code>.User.Team team = 4;</code>
         * @return Whether the team field is set.
         */
        @java.lang.Override
        public boolean hasTeam() {
            return team_ != null;
        }
        /**
         * <code>.User.Team team = 4;</code>
         * @return The team.
         */
        @java.lang.Override
        public UserFromProto.User.Team getTeam() {
            return team_ == null ? UserFromProto.User.Team.getDefaultInstance() : team_;
        }
        /**
         * <code>.User.Team team = 4;</code>
         */
        @java.lang.Override
        public UserFromProto.User.TeamOrBuilder getTeamOrBuilder() {
            return getTeam();
        }

        public static final int TEAM_LIST_FIELD_NUMBER = 5;
        private java.util.List<UserFromProto.User.Team> teamList_;
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        @java.lang.Override
        public java.util.List<UserFromProto.User.Team> getTeamListList() {
            return teamList_;
        }
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        @java.lang.Override
        public java.util.List<? extends UserFromProto.User.TeamOrBuilder>
        getTeamListOrBuilderList() {
            return teamList_;
        }
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        @java.lang.Override
        public int getTeamListCount() {
            return teamList_.size();
        }
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        @java.lang.Override
        public UserFromProto.User.Team getTeamList(int index) {
            return teamList_.get(index);
        }
        /**
         * <code>repeated .User.Team team_list = 5;</code>
         */
        @java.lang.Override
        public UserFromProto.User.TeamOrBuilder getTeamListOrBuilder(
                int index) {
            return teamList_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getUsernameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
            }
            if (!getSexBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sex_);
            }
            if (age_ != 0) {
                output.writeInt32(3, age_);
            }
            if (team_ != null) {
                output.writeMessage(4, getTeam());
            }
            for (int i = 0; i < teamList_.size(); i++) {
                output.writeMessage(5, teamList_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getUsernameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
            }
            if (!getSexBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sex_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, age_);
            }
            if (team_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getTeam());
            }
            for (int i = 0; i < teamList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, teamList_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UserFromProto.User)) {
                return super.equals(obj);
            }
            UserFromProto.User other = (UserFromProto.User) obj;

            if (!getUsername()
                    .equals(other.getUsername())) return false;
            if (!getSex()
                    .equals(other.getSex())) return false;
            if (getAge()
                    != other.getAge()) return false;
            if (hasTeam() != other.hasTeam()) return false;
            if (hasTeam()) {
                if (!getTeam()
                        .equals(other.getTeam())) return false;
            }
            if (!getTeamListList()
                    .equals(other.getTeamListList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + USERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getUsername().hashCode();
            hash = (37 * hash) + SEX_FIELD_NUMBER;
            hash = (53 * hash) + getSex().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            if (hasTeam()) {
                hash = (37 * hash) + TEAM_FIELD_NUMBER;
                hash = (53 * hash) + getTeam().hashCode();
            }
            if (getTeamListCount() > 0) {
                hash = (37 * hash) + TEAM_LIST_FIELD_NUMBER;
                hash = (53 * hash) + getTeamListList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static UserFromProto.User parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static UserFromProto.User parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static UserFromProto.User parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static UserFromProto.User parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static UserFromProto.User parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static UserFromProto.User parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static UserFromProto.User parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static UserFromProto.User parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static UserFromProto.User parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static UserFromProto.User parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static UserFromProto.User parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static UserFromProto.User parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(UserFromProto.User prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code User}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:User)
                UserFromProto.UserOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return UserFromProto.internal_static_User_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return UserFromProto.internal_static_User_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UserFromProto.User.class, UserFromProto.User.Builder.class);
            }

            // Construct using UserFromProto.User.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getTeamListFieldBuilder();
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                username_ = "";

                sex_ = "";

                age_ = 0;

                if (teamBuilder_ == null) {
                    team_ = null;
                } else {
                    team_ = null;
                    teamBuilder_ = null;
                }
                if (teamListBuilder_ == null) {
                    teamList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    teamListBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return UserFromProto.internal_static_User_descriptor;
            }

            @java.lang.Override
            public UserFromProto.User getDefaultInstanceForType() {
                return UserFromProto.User.getDefaultInstance();
            }

            @java.lang.Override
            public UserFromProto.User build() {
                UserFromProto.User result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public UserFromProto.User buildPartial() {
                UserFromProto.User result = new UserFromProto.User(this);
                int from_bitField0_ = bitField0_;
                result.username_ = username_;
                result.sex_ = sex_;
                result.age_ = age_;
                if (teamBuilder_ == null) {
                    result.team_ = team_;
                } else {
                    result.team_ = teamBuilder_.build();
                }
                if (teamListBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        teamList_ = java.util.Collections.unmodifiableList(teamList_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.teamList_ = teamList_;
                } else {
                    result.teamList_ = teamListBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UserFromProto.User) {
                    return mergeFrom((UserFromProto.User)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UserFromProto.User other) {
                if (other == UserFromProto.User.getDefaultInstance()) return this;
                if (!other.getUsername().isEmpty()) {
                    username_ = other.username_;
                    onChanged();
                }
                if (!other.getSex().isEmpty()) {
                    sex_ = other.sex_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (other.hasTeam()) {
                    mergeTeam(other.getTeam());
                }
                if (teamListBuilder_ == null) {
                    if (!other.teamList_.isEmpty()) {
                        if (teamList_.isEmpty()) {
                            teamList_ = other.teamList_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureTeamListIsMutable();
                            teamList_.addAll(other.teamList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.teamList_.isEmpty()) {
                        if (teamListBuilder_.isEmpty()) {
                            teamListBuilder_.dispose();
                            teamListBuilder_ = null;
                            teamList_ = other.teamList_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            teamListBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getTeamListFieldBuilder() : null;
                        } else {
                            teamListBuilder_.addAllMessages(other.teamList_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UserFromProto.User parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UserFromProto.User) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object username_ = "";
            /**
             * <code>string username = 1;</code>
             * @return The username.
             */
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string username = 1;</code>
             * @return The bytes for username.
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string username = 1;</code>
             * @param value The username to set.
             * @return This builder for chaining.
             */
            public Builder setUsername(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                username_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string username = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearUsername() {

                username_ = getDefaultInstance().getUsername();
                onChanged();
                return this;
            }
            /**
             * <code>string username = 1;</code>
             * @param value The bytes for username to set.
             * @return This builder for chaining.
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                username_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object sex_ = "";
            /**
             * <code>string sex = 2;</code>
             * @return The sex.
             */
            public java.lang.String getSex() {
                java.lang.Object ref = sex_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    sex_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string sex = 2;</code>
             * @return The bytes for sex.
             */
            public com.google.protobuf.ByteString
            getSexBytes() {
                java.lang.Object ref = sex_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    sex_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string sex = 2;</code>
             * @param value The sex to set.
             * @return This builder for chaining.
             */
            public Builder setSex(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                sex_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string sex = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearSex() {

                sex_ = getDefaultInstance().getSex();
                onChanged();
                return this;
            }
            /**
             * <code>string sex = 2;</code>
             * @param value The bytes for sex to set.
             * @return This builder for chaining.
             */
            public Builder setSexBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                sex_ = value;
                onChanged();
                return this;
            }

            private int age_ ;
            /**
             * <code>int32 age = 3;</code>
             * @return The age.
             */
            @java.lang.Override
            public int getAge() {
                return age_;
            }
            /**
             * <code>int32 age = 3;</code>
             * @param value The age to set.
             * @return This builder for chaining.
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 age = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            private UserFromProto.User.Team team_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    UserFromProto.User.Team, UserFromProto.User.Team.Builder, UserFromProto.User.TeamOrBuilder> teamBuilder_;
            /**
             * <code>.User.Team team = 4;</code>
             * @return Whether the team field is set.
             */
            public boolean hasTeam() {
                return teamBuilder_ != null || team_ != null;
            }
            /**
             * <code>.User.Team team = 4;</code>
             * @return The team.
             */
            public UserFromProto.User.Team getTeam() {
                if (teamBuilder_ == null) {
                    return team_ == null ? UserFromProto.User.Team.getDefaultInstance() : team_;
                } else {
                    return teamBuilder_.getMessage();
                }
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            public Builder setTeam(UserFromProto.User.Team value) {
                if (teamBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    team_ = value;
                    onChanged();
                } else {
                    teamBuilder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            public Builder setTeam(
                    UserFromProto.User.Team.Builder builderForValue) {
                if (teamBuilder_ == null) {
                    team_ = builderForValue.build();
                    onChanged();
                } else {
                    teamBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            public Builder mergeTeam(UserFromProto.User.Team value) {
                if (teamBuilder_ == null) {
                    if (team_ != null) {
                        team_ =
                                UserFromProto.User.Team.newBuilder(team_).mergeFrom(value).buildPartial();
                    } else {
                        team_ = value;
                    }
                    onChanged();
                } else {
                    teamBuilder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            public Builder clearTeam() {
                if (teamBuilder_ == null) {
                    team_ = null;
                    onChanged();
                } else {
                    team_ = null;
                    teamBuilder_ = null;
                }

                return this;
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            public UserFromProto.User.Team.Builder getTeamBuilder() {

                onChanged();
                return getTeamFieldBuilder().getBuilder();
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            public UserFromProto.User.TeamOrBuilder getTeamOrBuilder() {
                if (teamBuilder_ != null) {
                    return teamBuilder_.getMessageOrBuilder();
                } else {
                    return team_ == null ?
                            UserFromProto.User.Team.getDefaultInstance() : team_;
                }
            }
            /**
             * <code>.User.Team team = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    UserFromProto.User.Team, UserFromProto.User.Team.Builder, UserFromProto.User.TeamOrBuilder>
            getTeamFieldBuilder() {
                if (teamBuilder_ == null) {
                    teamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            UserFromProto.User.Team, UserFromProto.User.Team.Builder, UserFromProto.User.TeamOrBuilder>(
                            getTeam(),
                            getParentForChildren(),
                            isClean());
                    team_ = null;
                }
                return teamBuilder_;
            }

            private java.util.List<UserFromProto.User.Team> teamList_ =
                    java.util.Collections.emptyList();
            private void ensureTeamListIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    teamList_ = new java.util.ArrayList<UserFromProto.User.Team>(teamList_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    UserFromProto.User.Team, UserFromProto.User.Team.Builder, UserFromProto.User.TeamOrBuilder> teamListBuilder_;

            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public java.util.List<UserFromProto.User.Team> getTeamListList() {
                if (teamListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(teamList_);
                } else {
                    return teamListBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public int getTeamListCount() {
                if (teamListBuilder_ == null) {
                    return teamList_.size();
                } else {
                    return teamListBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public UserFromProto.User.Team getTeamList(int index) {
                if (teamListBuilder_ == null) {
                    return teamList_.get(index);
                } else {
                    return teamListBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder setTeamList(
                    int index, UserFromProto.User.Team value) {
                if (teamListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTeamListIsMutable();
                    teamList_.set(index, value);
                    onChanged();
                } else {
                    teamListBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder setTeamList(
                    int index, UserFromProto.User.Team.Builder builderForValue) {
                if (teamListBuilder_ == null) {
                    ensureTeamListIsMutable();
                    teamList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    teamListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder addTeamList(UserFromProto.User.Team value) {
                if (teamListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTeamListIsMutable();
                    teamList_.add(value);
                    onChanged();
                } else {
                    teamListBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder addTeamList(
                    int index, UserFromProto.User.Team value) {
                if (teamListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTeamListIsMutable();
                    teamList_.add(index, value);
                    onChanged();
                } else {
                    teamListBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder addTeamList(
                    UserFromProto.User.Team.Builder builderForValue) {
                if (teamListBuilder_ == null) {
                    ensureTeamListIsMutable();
                    teamList_.add(builderForValue.build());
                    onChanged();
                } else {
                    teamListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder addTeamList(
                    int index, UserFromProto.User.Team.Builder builderForValue) {
                if (teamListBuilder_ == null) {
                    ensureTeamListIsMutable();
                    teamList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    teamListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder addAllTeamList(
                    java.lang.Iterable<? extends UserFromProto.User.Team> values) {
                if (teamListBuilder_ == null) {
                    ensureTeamListIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, teamList_);
                    onChanged();
                } else {
                    teamListBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder clearTeamList() {
                if (teamListBuilder_ == null) {
                    teamList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    teamListBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public Builder removeTeamList(int index) {
                if (teamListBuilder_ == null) {
                    ensureTeamListIsMutable();
                    teamList_.remove(index);
                    onChanged();
                } else {
                    teamListBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public UserFromProto.User.Team.Builder getTeamListBuilder(
                    int index) {
                return getTeamListFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public UserFromProto.User.TeamOrBuilder getTeamListOrBuilder(
                    int index) {
                if (teamListBuilder_ == null) {
                    return teamList_.get(index);  } else {
                    return teamListBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public java.util.List<? extends UserFromProto.User.TeamOrBuilder>
            getTeamListOrBuilderList() {
                if (teamListBuilder_ != null) {
                    return teamListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(teamList_);
                }
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public UserFromProto.User.Team.Builder addTeamListBuilder() {
                return getTeamListFieldBuilder().addBuilder(
                        UserFromProto.User.Team.getDefaultInstance());
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public UserFromProto.User.Team.Builder addTeamListBuilder(
                    int index) {
                return getTeamListFieldBuilder().addBuilder(
                        index, UserFromProto.User.Team.getDefaultInstance());
            }
            /**
             * <code>repeated .User.Team team_list = 5;</code>
             */
            public java.util.List<UserFromProto.User.Team.Builder>
            getTeamListBuilderList() {
                return getTeamListFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    UserFromProto.User.Team, UserFromProto.User.Team.Builder, UserFromProto.User.TeamOrBuilder>
            getTeamListFieldBuilder() {
                if (teamListBuilder_ == null) {
                    teamListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            UserFromProto.User.Team, UserFromProto.User.Team.Builder, UserFromProto.User.TeamOrBuilder>(
                            teamList_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    teamList_ = null;
                }
                return teamListBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:User)
        }

        // @@protoc_insertion_point(class_scope:User)
        private static final UserFromProto.User DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new UserFromProto.User();
        }

        public static UserFromProto.User getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<User>
                PARSER = new com.google.protobuf.AbstractParser<User>() {
            @java.lang.Override
            public User parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new User(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<User> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<User> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public UserFromProto.User getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_User_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_User_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_User_Team_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_User_Team_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\025user-from-proto.proto\"\232\001\n\004User\022\020\n\010user" +
                        "name\030\001 \001(\t\022\013\n\003sex\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\030\n\004" +
                        "team\030\004 \001(\0132\n.User.Team\022\035\n\tteam_list\030\005 \003(" +
                        "\0132\n.User.Team\032-\n\004Team\022\013\n\003ceo\030\001 \001(\t\022\013\n\003ct" +
                        "o\030\002 \001(\t\022\013\n\003cfo\030\003 \001(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_User_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_User_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_User_descriptor,
                new java.lang.String[] { "Username", "Sex", "Age", "Team", "TeamList", });
        internal_static_User_Team_descriptor =
                internal_static_User_descriptor.getNestedTypes().get(0);
        internal_static_User_Team_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_User_Team_descriptor,
                new java.lang.String[] { "Ceo", "Cto", "Cfo", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}